rabbitmq:
  image:  rabbitmq
  container_name:  rabbitmq
  environment:
    hostname: my-rabbitmq
  ports:
    - 4369:4369
    - 5671:5671
    - 5672:5672
    - 25672:25672
    - 15671:15671
    - 15672:15672
  volumes:
    - /home/docker/container/rabbitmq:/var/lib/rabbitmq
  restart:  always
  privileged:  true